=== kaapana/kaapana/lib/task_api/task_api/processing_container/schemas/Task.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Task",
  "type": "object",
  "required": [
    "name",
    "image",
    "inputs",
    "outputs"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "command": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inputs": {
      "type": "array",
      "items": { "$ref": "IOVolume.schema.json" },
      "default": []
    },
    "outputs": {
      "type": "array",
      "items": { "$ref": "IOVolume.schema.json" },
      "default": []
    },
    "env": {
      "type": "array",
      "items": { "$ref": "ContainerEnvVar.schema.json" },
      "default": []
      },
    "resources": { "$ref": "Resources.schema.json" },
    "namespace": {
      "type": "string"
    },
    "registryUrl": {
      "type": "string"
    },
    "registryUsername": {
      "type": "string"
    },
    "registryPassword": {
      "type": "string"
    },
    "imagePullSecrets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== kaapana/kaapana/lib/taskctl/container_templates/dummy/tasks/test_task.json
{
    "name": "Kubernetes task for dummy image",
    "image": "{{ custom.registry }}/dummy:latest",
    "inputs": [],
    "outputs": [
        {   
            "name": "channel1",
            "input": {
                "local_path": "{{ custom.output_dir }}/dummy/channel1"
            }
        },
        {   
            "name": "channel2",
            "input": {
                "local_path": "{{ custom.output_dir }}/dummy/channel2"
            }
        }
    ],
    "env": [{
        "name":"TIME_SLEEP",
        "value": "1"
    },
    {
        "name": "DUMMY",
        "value": "dummy"
    }],
    "namespace": "default",
    "imagePullSecrets": ["registry-secret"]
}

=== kaapana/kaapana/lib/task_api/task_api/container_templates/dummy/tasks/test_env_task.json
{
    "name": "Kubernetes task for dummy image",
    "image": "{{ env.registry }}/dummy:latest",
    "inputs": [],
    "outputs": [
        {   
            "name": "channel1",
            "input": {
                "local_path": "{{ env.output_dir }}/env/channel1"
            }
        },
        {   
            "name": "channel2",
            "input": {
                "local_path": "{{ env.output_dir }}/env/channel2"
            }
        }
    ],
    "env": [{
        "name":"TIME_SLEEP",
        "value": "1"
    },
    {
        "name": "DUMMY",
        "value": "dummy"
    }],
    "namespace": "default",
    "imagePullSecrets": ["registry-secret"]
}
