=== kaapana/kaapana/lib/taskctl/taskctl/processing_container/schemas/ProcessingContainer.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ProcessingContainer",
  "type": "object",
  "required": [
      "name",
      "inputs",
      "description",
      "outputs",
      "command",
      "env"
  ],
  "properties": {
    "name": {
      "type": "string"
      },
    "description": {
      "type": "string"
      },
    "command": {
      "type": "array",
      "items": {
          "type": "string"
      }
    },
    "inputs": {
      "type": "array",
      "items": { "$ref": "IOMount.schema.json" },
      "default": []
      },
    "outputs": {
      "type": "array",
      "items": { "$ref": "IOMount.schema.json" },
      "default": []
      },
    "env": {
      "type": "array",
      "items": { "$ref": "ContainerEnvVar.schema.json" },
      "default": []
      },
    "resources": { "$ref": "Resources.schema.json" }
    }
}

=== kaapana/kaapana/lib/task_api/task_api/container_templates/downstream/processing-container.json
{
    "name": "Dummy-processing-container",
    "description": "Dummy processing container",
    "env": [],
    "inputs": [
        {
            "name": "channel1",
            "mounted_path":"/home/downstream/channel1"
        },
        {
            "name": "channel2",
            "mounted_path":"/home/downstream/channel2"
        }
    ],
    "outputs": [],
    "command": [
        "python3",
        "-u",
        "start.py"
    ]
}
